apiVersion: v1
kind: Service
metadata:
  name: customersvc
spec:
  type: NodePort
  selector:
    app: customer-backend
  ports:
    - name: customer-backend-port
      port: 80
      targetPort: 8080