apiVersion: apps/v1
kind: Deployment
metadata:
  name: customersvc-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-backend
  template:
    metadata:
      labels:
        app: customer-backend
    spec:
      containers:
        - name: customer-backend
          image: 840658508063.dkr.ecr.us-east-2.amazonaws.com/mc-kube:customersvc-v1
          ports:
            - containerPort: 80